# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IEEEKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('parent_keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IEEEKeywords')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('link', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], max_length=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanelMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('U', 'Not yet decided'), ('Y', 'Approved'), ('N', 'Declined')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTypes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status_message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('abstract', models.TextField(max_length=500, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StatusTypes')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisGuides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('G', 'Guide'), ('C', 'Co-Guide')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IEEEKeywords')),
                ('thesis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thesis')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('S', 'Student'), ('G', 'Guide'), ('D', 'Director'), ('R', 'Referee')], max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='thesisguides',
            name='guide_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='thesisguides',
            name='thesis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thesis'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='panelmembers',
            name='refereee_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='panelmembers',
            name='thesis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thesis'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterUniqueTogether(
            name='thesiskeywords',
            unique_together=set([('thesis_id', 'keyword_id')]),
        ),
    ]
