# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approver',
            old_name='user',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='thesis',
            old_name='user',
            new_name='student',
        ),
    ]
