# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Director', 'Director'), ('Other', 'Other')], default='Prof', max_length=30, verbose_name='Your Designation'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Director', 'Director'), ('Other', 'Other')], default='Prof', max_length=30, verbose_name='Your Designation'),
        ),
    ]
