# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170317_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieeekeywords',
            options={'verbose_name': 'IEEE Keyword', 'verbose_name_plural': 'IEEE Keywords'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='panelmembers',
            options={'verbose_name': 'Panel Member', 'verbose_name_plural': 'Panel Members'},
        ),
        migrations.AlterModelOptions(
            name='statustypes',
            options={'verbose_name': 'Status Type', 'verbose_name_plural': 'Status Types'},
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'Thesis', 'verbose_name_plural': 'Thesis'},
        ),
        migrations.AlterModelOptions(
            name='thesisguides',
            options={'verbose_name': 'Thesis Guide', 'verbose_name_plural': 'Thesis Guides'},
        ),
        migrations.AlterModelOptions(
            name='thesiskeywords',
            options={'verbose_name': 'Thesis Keyword', 'verbose_name_plural': 'Thesis Keywords'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='panelmembers',
            old_name='refereee_username',
            new_name='referee_username',
        ),
    ]
