# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170330_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='synopsis',
            field=models.FileField(blank=True, null=True, upload_to='Synopsis'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis',
            field=models.FileField(blank=True, null=True, upload_to='Thesis'),
        ),
    ]
