# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170318_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='username',
        ),
        migrations.AddField(
            model_name='notifications',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app.User'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.User'),
        ),
    ]
