# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170330_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='foreign_referees_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='thesis',
            name='indian_referees_required',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
