# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170320_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='synopsis',
            field=models.FileField(null=True, upload_to='Synopsis'),
        ),
    ]
