# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 18:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20170401_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.AddField(
            model_name='panelmember',
            name='feedback_at',
            field=models.CharField(choices=[('A', 'Admin'), ('G', 'Guide')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='feedback_with_referee_details',
            field=models.FileField(blank=True, null=True, upload_to='Feedback_With_Details'),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='feedback_without_referee_details',
            field=models.FileField(blank=True, null=True, upload_to='Feedback_Without_Details'),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 4, 16, 18, 6, 40, 532372, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panelmember',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='panelmember',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('G', 'Approved by guides'), ('N', 'Invite not sent'), ('S', 'Invite Sent'), ('A', 'Approved'), ('R', 'Rejected'), ('F', 'FeedbackSubmitted'), ('Z', 'FeedbackSubmitted and need Re-Evaluation')], max_length=1),
        ),
    ]
