# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_thesis_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='thesis',
            field=models.FileField(null=True, upload_to='Thesis'),
        ),
    ]
