# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170416_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Director', 'Director'), ('Other', 'Other')], default='Prof', max_length=30, verbose_name='Your Designation')),
                ('website', models.CharField(max_length=150)),
            ],
        ),
    ]
