# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='website',
        ),
        migrations.AddField(
            model_name='sample',
            name='phone_number',
            field=models.CharField(default='+91-', max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91-9830098300'. +91 is the country code of India.", regex='^\\+91-\\d{10}$')], verbose_name='Mobile Number'),
        ),
    ]
