# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170418_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
