# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_statustypes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisGuideApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Abstract'), ('S', 'Synopsis'), ('T', 'Thesis')], max_length=1)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thesis')),
            ],
            options={
                'verbose_name': 'Thesis Guide Approval',
                'verbose_name_plural': 'Thesis Guide Approvals',
            },
        ),
        migrations.RemoveField(
            model_name='statustypes',
            name='description',
        ),
    ]
