# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170418_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Director', 'Director'), ('Other', 'Other')], default='Prof', max_length=30, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='website',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
