# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_referees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referees',
            options={'verbose_name': 'Referee', 'verbose_name_plural': 'Referees'},
        ),
        migrations.AlterField(
            model_name='panelmembers',
            name='status',
            field=models.CharField(choices=[('P', 'Pending member'), ('U', 'Not yet decided'), ('Y', 'Approved'), ('N', 'Declined')], max_length=1),
        ),
    ]
