# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170418_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Faculty'),
        ),
    ]
