# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_referee_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
