# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170324_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('A', 'Accepeted'), ('P', 'Pending')], max_length=1)),
                ('referee_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('thesis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thesis')),
            ],
            options={
                'verbose_name': 'Final Panel',
                'verbose_name_plural': 'Final Panel',
            },
        ),
        migrations.CreateModel(
            name='NoEntryPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('thesis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Thesis')),
            ],
        ),
        migrations.RemoveField(
            model_name='panelmembers',
            name='priority',
        ),
        migrations.AlterField(
            model_name='panelmembers',
            name='status',
            field=models.CharField(choices=[('P', 'Pending member'), ('N', 'Not yet decided'), ('A', 'Approved'), ('D', 'Declined')], max_length=1),
        ),
    ]
